[build]
  command = "npm run build"
  publish = "_site"

[dev]
  command = "npm start"
  targetPort = 8080
  publish = "_site"
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 